spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: hydra
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

aws:
  s3:
    perf-test-bucket:
      name: skadi-query-cache-test-gp-unver
      arn: arn:aws:s3:::skadi-query-cache-test-gp-unver

    do-delete-test-s3-objects: true # set to false to leave test objects for debug

skadi:
  local:
    cacheRootDir: data/skadi-cache
    cacheMaxSize: 1Gb # 10 GB